<?php

/**
 * @file
 * Hooks et fonctions de base pour le module eth_balance.
 */

/**
 * Implements hook_theme().
 */
function eth_balance_theme($existing, $type, $theme, $path) {
  return [
    'eth_balance_block' => [
      'variables' => [
        'address'  => NULL,
        'balance'  => NULL,
  // ← on l’ajoute ici
        'endpoint' => NULL,
      ],
      'template' => 'eth-balance-block',
      'path'     => $path . '/templates',
    ],
  ];
}
