services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: "2g"
    environment:
      - SE_NODE_MAX_SESSIONS=1
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    networks:
      - default
